---

sudo: required
dist: xenial

language: python

before_install:
  - sudo apt-get update
  - sudo apt-get install libmms0 libjansson4
  - wget https://mediaarea.net/download/binary/libzen0/0.4.35/libzen0_0.4.35-1_amd64.xUbuntu_14.04.deb
  - sudo dpkg -i libzen0_0.4.35-1_amd64.xUbuntu_14.04.deb
  - wget https://mediaarea.net/download/binary/libmediainfo0/0.7.94/libmediainfo0_0.7.94-1_amd64.xUbuntu_14.04.deb
  - sudo dpkg -i libmediainfo0_0.7.94-1_amd64.xUbuntu_14.04.deb
  - wget https://mediaarea.net/download/binary/mediaconch/17.03/mediaconch_17.03-1_amd64.xUbuntu_14.04.deb
  - sudo dpkg -i mediaconch_17.03-1_amd64.xUbuntu_14.04.deb

before_script:
  - pip install tox

script: tox

notifications:
  email: false

matrix:
  include:
    - python: "2.7"
      env: TOXENV=py27
    - python: "3.6"
      env: TOXENV=py36
    - python: "3.7"
      env: TOXENV=py37
    - python: "3.8"
      env: TOXENV=py38
    - python: "3.7"
      env: TOXENV=linting
